on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the app
        run: gradle wrapper assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Rename APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} app/build/outputs/apk/release/HappyShare.apk
          
      - uses: actions/upload-artifact@v2
        name: Upload signed app artifact
        with:
          name: HappyShare.apk
          path: app/build/outputs/apk/release/HappyShare.apk

      - name: set env
        run: echo "NOW=v$(date +'%Y%m%d.%H%M')" >> $GITHUB_ENV
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/HappyShare.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release master
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          files: app/build/outputs/apk/release/HappyShare.apk
          tag_name: ${{ env.NOW }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}